#!/usr/bin/env bash
###----In PROGRESS NOT COMPLETED----
# modifying the default transfer file code to this format:
# a prompt to include file_transfer path
# a prompt to chose 1 of 3 server (01/02/03) each would be assigned an ip address.
# a prompt to ask if key_path is the default i.e ~/.ssh/id_rsa, if no allow user to enter key_path.
# finally transfer files

if [ $# -lt 1 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE";
    exit;
fi;

read -p "Enter the path to file_transfer: " file_transfer_path

echo "Choose one of the following servers:"
echo "01"
echo "02"
echo "03"
read -p "Enter the server number: " server_number

if [ "$server_number" == "01" ];
then
    ip_address="192.168.1.1"
elif [ "$server_number" == "02" ];
then
    ip_address="192.168.1.2"
elif [ "$server_number" == "03" ];
then
    ip_address="192.168.1.3"
else
    echo "Invalid server number entered."
    exit;
fi;

read -p "Is the key path the default i.e ~/.ssh/id_rsa? (y/n): " default_key_path

if [ "$default_key_path" == "n" ];
then
    read -p "Enter the path to SSH key: " ssh_key_path
else
    ssh_key_path="~/.ssh/id_rsa"
fi;

read -p "Enter the username: " username

# to debug add verbose i.e scp -v -o
if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_transfer_path" "$username"@"$ip_address":~/
else
    scp -o StrictHostKeyChecking=no "$file_transfer_path" "$username"@"$ip_address":~/
fi;
